import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const TopicSuggestionBox = ({ suggestedTopics, selectedTopic, onTopicSelect, tunedAudience, onAudienceChange, overallExplanation, onApply, onIgnore, allTopics, }) => {
    return (_jsxs("div", { className: "mb-3 p-3 bg-primary/10 border border-primary/30 rounded-lg", children: [_jsxs("div", { className: "mb-3", children: [_jsx("p", { className: "text-sm text-textPrimary mb-3", children: overallExplanation }), _jsxs("div", { className: "mb-3", children: [_jsx("label", { className: "block text-xs font-medium text-textMuted mb-2", children: "Suggested Topics (select one):" }), _jsx("div", { className: "space-y-2 mb-2", children: suggestedTopics.map((suggestion, index) => (_jsxs("label", { className: `flex items-start gap-2 p-2 rounded border cursor-pointer transition-colors ${selectedTopic === suggestion.topic
                                        ? 'bg-primary/20 border-primary/50'
                                        : 'bg-background/50 border-border hover:bg-background/70'}`, children: [_jsx("input", { type: "radio", name: "suggested-topic", value: suggestion.topic, checked: selectedTopic === suggestion.topic, onChange: () => onTopicSelect(suggestion.topic), className: "mt-1" }), _jsxs("div", { className: "flex-1", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsxs("span", { className: "text-sm font-semibold text-textPrimary", children: ["#", suggestion.topic] }), suggestion.isUserTopic && (_jsx("span", { className: "px-1.5 py-0.5 text-xs bg-primary/30 text-primary rounded", children: "Your topic" })), _jsxs("span", { className: "text-xs text-textMuted", children: [(suggestion.confidence * 100).toFixed(0), "% match"] })] }), _jsx("p", { className: "text-xs text-textMuted mt-0.5", children: suggestion.explanation })] })] }, suggestion.topic))) }), _jsxs("div", { className: "mt-2", children: [_jsx("label", { className: "block text-xs font-medium text-textMuted mb-1", children: "Or choose manually:" }), _jsxs("select", { value: selectedTopic || '', onChange: (e) => {
                                            if (e.target.value) {
                                                onTopicSelect(e.target.value);
                                            }
                                        }, className: "w-full px-3 py-1.5 text-sm bg-background border border-border rounded text-textPrimary focus:border-primary focus:outline-none", children: [_jsx("option", { value: "", children: "Select a topic..." }), allTopics.map((topic) => (_jsxs("option", { value: topic, children: ["#", topic] }, topic)))] })] })] }), selectedTopic && (_jsxs("div", { className: "mb-3 pt-3 border-t border-border", children: [_jsx("label", { className: "block text-xs font-medium text-textMuted mb-2", children: "Reach Settings:" }), _jsxs("div", { className: "flex flex-wrap gap-3 text-xs", children: [_jsxs("label", { className: "flex items-center gap-1.5 text-textMuted cursor-pointer", children: [_jsx("input", { type: "checkbox", checked: tunedAudience.allowFollowers, onChange: (e) => onAudienceChange({ ...tunedAudience, allowFollowers: e.target.checked }), className: "rounded" }), _jsx("span", { className: tunedAudience.allowFollowers ? 'text-textPrimary' : '', children: "Allow Followers" })] }), _jsxs("label", { className: "flex items-center gap-1.5 text-textMuted cursor-pointer", children: [_jsx("input", { type: "checkbox", checked: tunedAudience.allowNonFollowers, onChange: (e) => onAudienceChange({ ...tunedAudience, allowNonFollowers: e.target.checked }), className: "rounded" }), _jsx("span", { className: tunedAudience.allowNonFollowers ? 'text-textPrimary' : '', children: "Allow Non-followers" })] })] })] }))] }), selectedTopic && (_jsxs("div", { className: "flex gap-2", children: [_jsx("button", { onClick: onApply, className: "px-3 py-1.5 text-xs bg-primary text-white rounded hover:bg-primary/90 transition-colors", children: "Apply & Post" }), _jsx("button", { onClick: onIgnore, className: "px-3 py-1.5 text-xs bg-background/50 text-textMuted rounded hover:bg-background/70 transition-colors", children: "Ignore" })] }))] }));
};
export default TopicSuggestionBox;
